---
name: Shira
surname: Salingre
position: "Data Specialist | Marine Scientist"
address: "Barcelona, Catalonia, Spain"
www: shirasal.github.io
email: "shira.salin@gmail.com"
phone: "+34-603-522-149"
github: shirasal
linkedin: shira-salingre
# aboutme: Turning DATA into KNOWLEDGE
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "74c5c3"
output: 
  vitae::awesomecv:
    page_total: true
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(vitae)
library(here)
library(kableExtra)

```

```{r functions}
readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  # save sheet name for each sheet (list)
  names(list) <- all
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}

```

```{r load-data, message=F, results='hide'}

filename <- here::here("shira_salingre_cv_data.xlsx")
readExcelSheets(filename)

```

<!-- # Professional Summary -->

<!-- # Resume Objective -->

# Short introduction

-   Data analyst with over 5 years experience in quantitative research (ecology).
-   Enthusiastic, curious, independent and organised, analytical thinker and with great communication skills.
-   Seeking to contribute to a good cause while working in a fun and supportive environment.

# Technical Skills

```{r}
skills %>% 
  mutate(Area = factor(Area, levels = c("Coding Languages", "Software", "Other"))) %>% 
  filter(Type == "Tech Stack") %>% 
  arrange(Area, desc(Proficiency)) %>% 
  select(Area, Skill) %>% 
  pivot_wider(names_from = Area, values_from = Skill, values_fn = list) %>% 
  kable(booktabs = T, align = "c", escape = F, format = "latex") %>%
  kable_styling(full_width = F, font_size = 9,latex_options = "hold_position") %>% 
  row_spec(0, bold = T, color = "#82bfbe", hline_after = F) %>% 
  row_spec(1, bold = F, color = "#7f7f7f") %>% 
  column_spec(column = 1:3, width = "5.5cm")

# skills %>% 
#   filter(Type == "Soft Skills") %>% 
#   brief_entries(what = Skill)
  
```

# Experience

```{r}
experience %>% 
  arrange(desc(end_date), start_date, institution) %>% 
  mutate(start_date = as.character(start_date)) %>% 
  mutate(when = if_else(start_date == end_date, start_date, paste(start_date, end_date, sep = "-"))) %>% 
  detailed_entries(what = institution,
                   when = when,
                   with = role,
                   where = where,
                   why = details)
```

# Education

```{r}
education %>% 
  vitae::brief_entries(what = degree,
                   when = year,
                   with = institution)

```

# Languages

```{r}
skills %>% 
  mutate(Area = factor(Area, levels = c("Coding Languages", "Software", "Other"))) %>% 
  filter(Type == "Language") %>% 
  arrange(Area, desc(Proficiency)) %>% 
  select(Skill, Proficiency) %>% 
  kable(booktabs = T, align = "l", format = "latex") %>%
  kable_styling(full_width = F, font_size = 9, latex_options = "hold_position") %>% 
  row_spec(0, bold = T, color = "#82bfbe", hline_after = F) %>% 
  column_spec(column = 1:2, width = "6cm")

  
```
